### ISSUE TITLE
Support for API Gateway V2 HTTP API payloads

### ISSUE THREAD

**Issue by tallpants** [vendia/serverless-express#279]
Difference between the payloads here: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html

[API Gateway HTTP APIs](https://aws.amazon.com/blogs/compute/announcing-http-apis-for-amazon-api-gateway/) (which have lower cost and latency compared to the standard API Gateway REST APIs) use this model by default, and aws-serverless-express doesn't work with it right now

**Comment by tallpants** [comment]
Note: for those who can't wait for this to be implemented -- you can manually select the old payload format by setting `PayloadFormatVersion` to `"1.0"` on the event in CloudFormation: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-httpapi.html#sam-function-httpapi-payloadformatversion

For example:

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/my-function
      Handler: index.handler
      Runtime: nodejs10.x
      Events:
        Get:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            PayloadFormatVersion: "1.0"
```
