### ISSUE TITLE
aws express only responding to default route

### ISSUE THREAD

**Issue by tejpowar** [vendia/serverless-express#311]
Hi

I have been trying to follow the example for the aws-serverless-express.

I have gone back to basics on this but am having issues with any additional routes. The default routes returns a simple "hello world" which is fine. When i add an additional route and browse to that it shows an "internal server error" message. Cloud watch does not show any logs so cannot diagnose.

My setup is as follows: 

**Apigateway:**

- HTTP
- NO AUTH
- CORS enabled

Lambda function which is shown below

app.js

```
`const express = require('express')
const app = express()
const bodyParser = require('body-parser')
const cors = require('cors')
const port = 3000
const awsServerlessExpressMiddleware = require('aws-serverless-express/middleware')
const router = express.Router()

router.use(cors())
router.use(bodyParser.json())
router.use(bodyParser.urlencoded({ extended: true }))
router.use(awsServerlessExpressMiddleware.eventContext())


const users = [{
    id: 1,
    name: 'Joe'
}, {
    id: 2,
    name: 'Jane'
}]

router.get('/test', (req, res) => {

    res.send('test World!')
})

router.get('/', (req, res) => {
    res.send('Hello World!')
})

router.get('/users', (req, res) => {
    console.log('users....');
    res.json(users)
})

app.use('/', router)

module.exports = app`
```

lambda.js

```
`const awsServerlessExpress = require('aws-serverless-express')
const app = require('./app')
const server = awsServerlessExpress.createServer(app)

exports.handler = (event, context) => { awsServerlessExpress.proxy(server, event, context) }`
```

Not sure what is causing the issue as the setup is simple.

Any ideas on this issue?

Thanks

**Comment by kadko** [comment]
try to browser your route with "/" to end of it or remove it if you use.

**Comment by bolddp** [comment]
@tejpowar Did you manage to fix this? I'm having the same problem.

**Comment by brettstack** [comment]
Were you using API Gateway's HTTP API (aka APIGW V2)?

Serverless Express v3 only support's API Gateway's REST API. However, if you upgrade to the latest RC of @vendia/serverless-express, there is experimental support for HTTP API.

**Comment by bolddp** [comment]
@brettstack Yes, it was due to the HTTP API incompatibility. It could be solved by reverting the API Gateway payload format in the CF stack, so I didn't have to switch back to API GW REST API:
```
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '1.0'
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '1.0'
            Path: /
            Method: ANY
```

Good to know that it's about to be solved in an upcoming release! 👍
