### ISSUE TITLE
Request Object Empty

### ISSUE THREAD

**Issue by VinyP** [vendia/serverless-express#318]
I was able to successfully upload my project following this [Tutorial](https://medium.com/cactus-techblog/deploy-angular-universal-on-aws-lambda-from-scratch-1b169289eac2). But i've come across a hair pulling bug and wanted to know if anyone was able to help. My goal is to redirect all "/api/**" calls to our current server, however when i try to grab the request params they are empty including request.body in POST calls. 

- I do see request object when i do a serverless offline, but not after deploying to aws.

serverless.ts 

```
import 'zone.js/dist/zone-node';
import { ngExpressEngine } from '@nguniversal/express-engine';
import * as express from 'express';
import { join } from 'path';
import { AppServerModule } from './src/main.server';
import { APP_BASE_HREF } from '@angular/common';
import { existsSync } from 'fs';
const bodyParser = require('body-parser')
const cors = require('cors')
export const app = express();
const distFolder = join(process.cwd(), 'dist/mainfront/browser');
const indexHtml = existsSync(join(distFolder, 'index.original.html')) ? 'index.original.html' : 'index';
// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
app.use(cors())
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({ extended: true }))

app.engine('html', ngExpressEngine({
    bootstrap: AppServerModule,
}));
app.set('view engine', 'html');
app.set('views', distFolder);

// Serve static files from /browser
app.get('*.*', express.static(distFolder, {
    maxAge: '2h'
}));

// All Redirects
app.all('/api/**', (req, res) => {
    let authToken = req.get('Authorization'); // token is empty
    res.append('authorization', `${authToken}`); // token is empty
    console.log(`<< API Redirect Data >> [${req.method}]: ${req.originalUrl}`, req.query, authToken) // req.query, or req.params are empty
    res.redirect(301,`https://www.example.com${req.originalUrl}`);
});

// All regular routes use the Universal engine
// DO not edit this
app.get('*', (req, res) => {
    res.render(indexHtml, { req, providers: [{ provide: APP_BASE_HREF, useValue: req.baseUrl }] });
});
export * from './src/main.server';

```
lambda.js
```
'use strict'
const awsServerlessExpress = require("aws-serverless-express");
const server = require("./dist/mainfront/serverless/main");
const awsServerlessExpressMiddleware = require("aws-serverless-express/middleware");
const binaryMimeTypes = [
  "application/javascript",
  "application/json",
  "application/octet-stream",
  "application/xml",
  "image/jpeg",
  "image/png",
  "image/gif",
  "text/comma-separated-values",
  "text/css",
  "text/html",
  "text/javascript",
  "text/plain",
  "text/text",
  "text/xml",
  "image/x-icon",
  "image/svg+xml",
  "application/x-font-ttf",
  "font/ttf",
  "font/otf",
];
server.app.use(awsServerlessExpressMiddleware.eventContext());
const serverProxy = awsServerlessExpress.createServer(
  server.app,
  null,
  binaryMimeTypes
);
module.exports.universal = (event, context) => {
  console.log(`EVENT: ${JSON.stringify(event)}`); // no request body, params, or authtoken
  awsServerlessExpress.proxy(serverProxy, event, context);
}
```

serverless.yml

```
service: mainfront
plugins:
  - serverless-apigw-binary
  - serverless-offline
provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 192
  region: us-east-1
  timeout: 10
  stage: production
package:
  exclude:
    - ./**
  include:
    - "node_modules/aws-serverless-express/**"
    - "node_modules/binary-case/**"
    - "node_modules/type-is/**"
    - "node_modules/media-typer/**"
    - "node_modules/mime-types/**"
    - "node_modules/mime-db/**"
    - "dist/**"
    - "lambda.js"
custom:
  apigwBinary:
    types:
      - "*/*"
functions:
  api:
    handler: lambda.universal
    events: 
        - http: 
            path: /
            method: ANY
            cors: true
        - http: 
            path: /{proxy+}
            method: ANY
            cors: true

```
